version: "3.9"
services:
#  mysql_db:
#    container_name: mysql_db
#    image: mysql:5.7
#    restart: always
#    environment:
#      - MYSQL_DATABASE=getground
#      - MYSQL_USER=guest
#      - MYSQL_PASSWORD=guest
#      - MYSQL_ROOT_PASSWORD=admin
#    ports:
#      - 3306:3306
#    volumes:
#      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"

  app:
    build:
      context: tennis-tournament
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "80:8080"
    volumes:
      - ./swagger/openSpec.yaml:/openSpec.yaml
    environment:
      SWAGGER_JSON: /openSpec.yaml